CREATE DATABASE IF NOT EXISTS university2;

USE university2;

CREATE TABLE IF NOT EXISTS t_timetable (
  F_TIMETABLE_ID int(11) NOT NULL AUTO_INCREMENT,
  F_COUNT_OF_ROOMS int(11) DEFAULT NULL,
  F_PAIRS_IN_DAY int(11) DEFAULT NULL,
  PRIMARY KEY (F_TIMETABLE_ID),
  UNIQUE KEY F_TIMETABLE_ID (F_TIMETABLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_user (
  F_USER_ID int(11) NOT NULL AUTO_INCREMENT,
  F_LOGIN varchar(255) DEFAULT NULL,
  F_NAME varchar(255) DEFAULT NULL,
  F_PASSWORD varchar(255) DEFAULT NULL,
  F_TIMETABLE_ID int(11) NOT NULL,
  PRIMARY KEY (F_USER_ID),
  UNIQUE KEY F_USER_ID (F_USER_ID),
  FOREIGN KEY (F_TIMETABLE_ID) REFERENCES t_timetable (F_TIMETABLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_admin (
  F_USER_ID int(11) NOT NULL,
  PRIMARY KEY (F_USER_ID),
  FOREIGN KEY (F_USER_ID) REFERENCES t_user (F_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_professor (
  F_USER_ID int(11) NOT NULL,
  PRIMARY KEY (F_USER_ID),
  FOREIGN KEY (F_USER_ID) REFERENCES t_user (F_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_request (
  F_REQUEST_ID int(11) NOT NULL AUTO_INCREMENT,
  F_DISCIPLINE varchar(255) DEFAULT NULL,
  F_PAIRS_IN_WEEK int(11) DEFAULT NULL,
  F_GROUP int(11) DEFAULT NULL,
  F_USER_ID int(11) NOT NULL,
  PRIMARY KEY (F_REQUEST_ID),
  UNIQUE KEY F_REQUEST_ID (F_REQUEST_ID),
  FOREIGN KEY (F_USER_ID) REFERENCES t_professor (F_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;